// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blog.Data;

#nullable disable

namespace blog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240723191040_addPostInCommentsCLass")]
    partial class addPostInCommentsCLass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("blog.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Já tamo lá!",
                            Name = "Topázio Pref.",
                            PostId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Simm, por isso sou swiftie",
                            Name = "I Love TS",
                            PostId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "O preço que se paga por saber ler...",
                            Name = "TheVeggieOne.",
                            PostId = 3
                        });
                });

            modelBuilder.Entity("blog.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Topazio calça as ruas do rio vermelho pelo amor de deussss",
                            Likes = 300,
                            Title = "Prefeitura de Florianópolis"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Que melancolia é essa, vai pra terapia moça",
                            Likes = 14,
                            Title = "Lana del rey"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Veganos obriagda por deixarem mais para nós HAHAYSAGDYUBGEDWUY",
                            Likes = 56,
                            Title = "Eu Amo Carne"
                        });
                });

            modelBuilder.Entity("blog.Models.Comments", b =>
                {
                    b.HasOne("blog.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("blog.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
