// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blog.Data;

#nullable disable

namespace blog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240725185426_ChangeNames")]
    partial class ChangeNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("blog.Models.Comments", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentLikes")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentContent = "Já tamo lá!",
                            CommentLikes = 12,
                            PostId = 1
                        },
                        new
                        {
                            CommentId = 2,
                            CommentContent = "Simm, por isso sou swiftie",
                            CommentLikes = 50,
                            PostId = 2
                        },
                        new
                        {
                            CommentId = 3,
                            CommentContent = "O preço que se paga por saber ler...",
                            CommentLikes = 6,
                            PostId = 3
                        });
                });

            modelBuilder.Entity("blog.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostLikes")
                        .HasColumnType("int");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("post");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            PostContent = "Topazio calça as ruas do rio vermelho pelo amor de deussss",
                            PostLikes = 300,
                            PostTitle = "Prefeitura de Florianópolis"
                        },
                        new
                        {
                            PostId = 2,
                            PostContent = "Que melancolia é essa, vai pra terapia moça",
                            PostLikes = 14,
                            PostTitle = "Lana del rey"
                        },
                        new
                        {
                            PostId = 3,
                            PostContent = "Veganos obriagda por deixarem mais para nósHAHAHA",
                            PostLikes = 56,
                            PostTitle = "Eu Amo Carne"
                        });
                });

            modelBuilder.Entity("blog.Models.Comments", b =>
                {
                    b.HasOne("blog.Models.Post", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("blog.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
